######################################################################
# Automatically generated by qmake (3.0) Sun Mar 30 10:39:23 2014
######################################################################

QT += widgets
TEMPLATE = app
TARGET = Frak
INCLUDEPATH += .

# Input
HEADERS += frakablak.h frakszal.h
SOURCES += frakablak.cpp frakszal.cpp main.cpp
